#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

. $WM_PROJECT_DIR/bin/tools/RunFunctions

touch Leveque.foam
wmake libso generateU

runApplication blockMesh
restore0Dir

runApplication setAlphaField
runApplication generateU

runApplication decomposePar
runParallel $(getApplication)
# mpirun -oversubscribe -np 4 $(getApplication) -parallel  > log.$(getApplication)

