#!/bin/bash

wmake libso src/interfaceCapturing
wmake libso src/surfaceForces

wmake libso src/postProcessing

wmake apps/setFieldfromTable
wmake apps/initAlphaField

wmake apps/benchmark/interfaceAdvector
wmake apps/benchmark/reconstructInterface

wmake solver/interCapturingFoam

