#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

. $WM_PROJECT_DIR/bin/tools/RunFunctions

touch discUniflow.foam

runApplication blockMesh
restore0Dir

runApplication setAlphaField

runApplication $(getApplication)
