#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

. $WM_PROJECT_DIR/bin/tools/RunFunctions

touch discUniflowTet.foam

runApplication gmshv493 -3 triSquare.geo
runApplication gmshToFoam triSquare.msh
runApplication changeDictionary 

restore0Dir

runApplication setAlphaField

runApplication $(getApplication)
