#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

. $WM_PROJECT_DIR/bin/tools/RunFunctions
touch vortexShearedDisc.foam

wmake libso generateUVortex2D

runApplication gmshv493 -3 triSquare.geo
runApplication gmshToFoam triSquare.msh
runApplication changeDictionary 
restore0Dir

runApplication setAlphaField
runApplication generateUVortex2D

runApplication decomposePar
runParallel $(getApplication)

