#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

. $WM_PROJECT_DIR/bin/tools/RunFunctions

touch LevequeTet.foam
wmake libso generateU

runApplication gmshv493 -3 triBlock.geo
runApplication gmshToFoam triBlock.msh
runApplication changeDictionary 
restore0Dir

runApplication setAlphaField
runApplication generateU

runApplication decomposePar
runParallel $(getApplication)
# mpirun -oversubscribe -np 4 $(getApplication) -parallel  > log.$(getApplication)

