#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

. $WM_PROJECT_DIR/bin/tools/RunFunctions


touch deform.foam
wmake libso generateUDeform

runApplication blockMesh
restore0Dir

runApplication setAlphaField
runApplication generateUDeform

runApplication decomposePar
runParallel $(getApplication)
